services:
  rest-api:
    image: enjin/blockchain-rest-api:local
    build: .
    read_only: true
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SAS_SUBSTRATE_URL: ${SAS_SUBSTRATE_URL:-wss://rpc.relay.blockchain.enjin.io}
      SAS_SUBSTRATE_MULTI_CHAIN_URL: ${SAS_SUBSTRATE_MULTI_CHAIN_URL:-[]}
      SAS_METRICS_ENABLED: "true"
